### ISSUE TITLE
'use' as method name is possible on php 7+

### ISSUE THREAD

**Issue by phudinsky** [CapMousse/React-Restify#16]
Hi.

It's impossible to run code with php < 7.0 because Server::use method crashes application. The reason is [restriction](http://php.net/manual/en/reserved.keywords.php) to use keywords as methods names.

I think it would be nice if you add version of php as requirements in composer.json or find another good name for this method :)

**Comment by CapMousse** [comment]
I need to do both : change `use` by `middleware` or an other name and update composer to require php 7+

**Comment by CapMousse** [comment]
Now, version 1.1.1 require php 7+ and add PSR-11 compatibilty : https://github.com/CapMousse/React-Restify/releases/tag/1.1.1
